-- =============================================
-- Migration 006: Add structured synthesis output columns
-- =============================================
-- Date: 2026-01-26
-- Purpose: Add new columns for Playing to Win synthesis system
-- =============================================

-- Add new columns to synthesis_outputs table
-- These support the structured JSON synthesis from the PTW framework

-- Make output_type nullable and remove CHECK constraint (legacy field)
ALTER TABLE synthesis_outputs
  ALTER COLUMN output_type DROP NOT NULL;

-- Drop the CHECK constraint on output_type to allow NULL values
-- The constraint name follows PostgreSQL's naming convention: table_column_check
ALTER TABLE synthesis_outputs
  DROP CONSTRAINT IF EXISTS synthesis_outputs_output_type_check;

-- Make title nullable (legacy field)
ALTER TABLE synthesis_outputs
  ALTER COLUMN title DROP NOT NULL;

-- Add synthesis content fields
ALTER TABLE synthesis_outputs
  ADD COLUMN IF NOT EXISTS synthesis_content TEXT;

ALTER TABLE synthesis_outputs
  ADD COLUMN IF NOT EXISTS synthesis_type TEXT CHECK (synthesis_type IN ('ai_generated', 'user_edited'));

ALTER TABLE synthesis_outputs
  ADD COLUMN IF NOT EXISTS executive_summary TEXT;

-- Add structured data arrays (JSONB)
ALTER TABLE synthesis_outputs
  ADD COLUMN IF NOT EXISTS opportunities JSONB DEFAULT '[]'::jsonb;

ALTER TABLE synthesis_outputs
  ADD COLUMN IF NOT EXISTS tensions JSONB DEFAULT '[]'::jsonb;

ALTER TABLE synthesis_outputs
  ADD COLUMN IF NOT EXISTS ptw_cascades JSONB DEFAULT '[]'::jsonb;

ALTER TABLE synthesis_outputs
  ADD COLUMN IF NOT EXISTS recommendations JSONB DEFAULT '[]'::jsonb;

-- Add metadata column (JSONB)
ALTER TABLE synthesis_outputs
  ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}'::jsonb;

-- Add user modification tracking
ALTER TABLE synthesis_outputs
  ADD COLUMN IF NOT EXISTS user_edited BOOLEAN DEFAULT FALSE;

ALTER TABLE synthesis_outputs
  ADD COLUMN IF NOT EXISTS edited_at TIMESTAMPTZ;

-- Add comment for documentation
COMMENT ON TABLE synthesis_outputs IS 'Stores AI-generated strategic synthesis using Playing to Win framework';
COMMENT ON COLUMN synthesis_outputs.synthesis_content IS 'Raw AI response text for debugging/fallback';
COMMENT ON COLUMN synthesis_outputs.synthesis_type IS 'Whether generated by AI or edited by user';
COMMENT ON COLUMN synthesis_outputs.executive_summary IS '2-3 sentence strategic summary';
COMMENT ON COLUMN synthesis_outputs.opportunities IS 'Array of StrategicOpportunity objects with scoring, evidence, assumptions';
COMMENT ON COLUMN synthesis_outputs.tensions IS 'Array of StrategicTension objects showing conflicting evidence';
COMMENT ON COLUMN synthesis_outputs.ptw_cascades IS 'Optional detailed Playing to Win cascades for top opportunities';
COMMENT ON COLUMN synthesis_outputs.recommendations IS 'Top 3 priority action recommendations';
COMMENT ON COLUMN synthesis_outputs.metadata IS 'Generation metadata including model, territories, confidence';
COMMENT ON COLUMN synthesis_outputs.user_edited IS 'Whether user has modified the AI output';
COMMENT ON COLUMN synthesis_outputs.edited_at IS 'Timestamp of last user edit';
