/**
 * Inline PDF generation script content (CommonJS).
 * This is written to /tmp at runtime and executed as a subprocess
 * to avoid dual React instance issues with @react-pdf/renderer in Next.js.
 */

/* eslint-disable */
export const PDF_SCRIPT_CONTENT = [
  'const { renderToBuffer, Document, Page, View, Text } = require("@react-pdf/renderer");',
  'const { createElement } = require("react");',
  'const h = createElement;',
  '',
  'function truncate(t, m) { if (!t) return ""; return t.length > m ? t.substring(0, m) + "..." : t; }',
  'function formatDate(d) { return new Date(d).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }); }',
  '',
  'var C = {',
  '  navy: { DEFAULT: "#1a1f3a", light: "#2d3561" },',
  '  gold: { DEFAULT: "#fbbf24", 50: "#fffbeb" },',
  '  cyan: { 50: "#ecfeff", 500: "#0891b2", 600: "#0891b2" },',
  '  slate: { 50: "#f8fafc", 100: "#f1f5f9", 200: "#e2e8f0", 300: "#cbd5e1", 400: "#94a3b8", 500: "#64748b", 600: "#475569", 700: "#334155", 800: "#1e293b", 900: "#0f172a" },',
  '  emerald: { 50: "#ecfdf5", 500: "#10b981", 600: "#059669" },',
  '  amber: { 50: "#fffbeb", 100: "#fef3c7", 500: "#f59e0b", 600: "#d97706" },',
  '  white: "#ffffff",',
  '};',
  '',
  'var S = {',
  '  page: { padding: 40, fontFamily: "Helvetica", fontSize: 10, color: C.slate[900], backgroundColor: C.white },',
  '  coverPage: { padding: 0, backgroundColor: C.white, display: "flex", flexDirection: "column", height: "100%" },',
  '  h2: { fontSize: 18, fontFamily: "Helvetica-Bold", color: C.slate[900], marginBottom: 12 },',
  '  h3: { fontSize: 13, fontFamily: "Helvetica-Bold", color: C.slate[800], marginBottom: 8 },',
  '  body: { fontSize: 10, lineHeight: 1.6, color: C.slate[700] },',
  '  bodySmall: { fontSize: 9, lineHeight: 1.5, color: C.slate[600] },',
  '  label: { fontSize: 8, fontFamily: "Helvetica-Bold", textTransform: "uppercase", letterSpacing: 1, color: C.slate[500] },',
  '  card: { backgroundColor: C.white, border: "1pt solid " + C.slate[200], borderRadius: 12, padding: 16, marginBottom: 12 },',
  '  cardHl: { backgroundColor: C.slate[50], border: "1pt solid " + C.slate[200], borderRadius: 12, padding: 16, marginBottom: 12 },',
  '  badge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 12, fontSize: 7, fontFamily: "Helvetica-Bold", textTransform: "uppercase", letterSpacing: 0.5 },',
  '  row: { flexDirection: "row", alignItems: "center" },',
  '  footer: { position: "absolute", bottom: 30, left: 40, right: 40, flexDirection: "row", justifyContent: "space-between", alignItems: "center", fontSize: 8, color: C.slate[400], borderTop: "1pt solid " + C.slate[200], paddingTop: 10 },',
  '  statCard: { flex: 1, backgroundColor: C.slate[50], borderRadius: 12, padding: 16, alignItems: "center" },',
  '  statNum: { fontSize: 32, fontFamily: "Helvetica-Bold", marginBottom: 4 },',
  '  statLabel: { fontSize: 8, fontFamily: "Helvetica-Bold", textTransform: "uppercase", letterSpacing: 1, color: C.slate[500] },',
  '};',
  '',
  'var QS = {',
  '  invest: { backgroundColor: C.emerald[50], color: C.emerald[600], borderColor: C.emerald[500] },',
  '  explore: { backgroundColor: C.gold[50], color: C.navy.DEFAULT, borderColor: C.navy.DEFAULT },',
  '  harvest: { backgroundColor: C.amber[50], color: C.amber[600], borderColor: C.amber[500] },',
  '  divest: { backgroundColor: C.slate[100], color: C.slate[600], borderColor: C.slate[400] },',
  '};',
  '',
  'function cover(client, date) {',
  '  return h(Page, { size: "A4", style: S.coverPage },',
  '    h(View, { style: { width: "100%", height: 8, backgroundColor: C.navy.DEFAULT } }),',
  '    h(View, { style: { flex: 1, padding: 60, display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center" } },',
  '      h(View, { style: { marginBottom: 40, alignItems: "center" } },',
  '        h(Text, { style: { fontSize: 36, fontFamily: "Helvetica-Bold", color: C.navy.DEFAULT, letterSpacing: 2 } }, "FRONTERA")',
  '      ),',
  '      h(View, { style: { backgroundColor: C.gold[50], paddingVertical: 8, paddingHorizontal: 16, borderRadius: 20, marginBottom: 24 } },',
  '        h(Text, { style: { fontSize: 10, fontFamily: "Helvetica-Bold", color: C.navy.DEFAULT, textTransform: "uppercase", letterSpacing: 1.5 } }, "STRATEGIC SYNTHESIS REPORT")',
  '      ),',
  '      h(Text, { style: { fontSize: 32, fontFamily: "Helvetica-Bold", color: C.slate[900], textAlign: "center", marginBottom: 12 } }, client?.company_name || "Strategy Report"),',
  '      client?.industry && h(View, { style: { backgroundColor: C.slate[100], paddingVertical: 6, paddingHorizontal: 12, borderRadius: 12 } },',
  '        h(Text, { style: { fontSize: 10, color: C.slate[600] } }, client.industry)',
  '      ),',
  '      h(Text, { style: { fontSize: 11, color: C.slate[400], marginTop: 32 } }, formatDate(date))',
  '    ),',
  '    h(View, { style: { padding: 40, borderTop: "1pt solid " + C.slate[200], alignItems: "center" } },',
  '      h(Text, { style: { fontSize: 9, color: C.slate[500] } }, "Generated by Frontera AI Strategy Coach")',
  '    )',
  '  );',
  '}',
  '',
  'function execSummary(syn, client, pn) {',
  '  return h(Page, { size: "A4", style: S.page },',
  '    h(View, { style: { marginBottom: 20 } },',
  '      h(View, { style: { flexDirection: "row", alignItems: "center", marginBottom: 8 } },',
  '        h(View, { style: { width: 4, height: 24, backgroundColor: C.navy.DEFAULT, borderRadius: 2, marginRight: 12 } }),',
  '        h(Text, { style: Object.assign({}, S.h2, { marginBottom: 0 }) }, "Executive Summary")',
  '      )',
  '    ),',
  '    h(View, { style: Object.assign({}, S.cardHl, { marginBottom: 24 }) },',
  '      h(Text, { style: Object.assign({}, S.body, { fontSize: 11, lineHeight: 1.7 }) }, syn.executiveSummary || "No executive summary available.")',
  '    ),',
  '    h(View, { style: Object.assign({}, S.row, { gap: 16, marginBottom: 24 }) },',
  '      h(View, { style: S.statCard }, h(Text, { style: Object.assign({}, S.statNum, { color: C.navy.DEFAULT }) }, String(syn.opportunities?.length || 0)), h(Text, { style: S.statLabel }, "OPPORTUNITIES")),',
  '      h(View, { style: S.statCard }, h(Text, { style: Object.assign({}, S.statNum, { color: C.amber[600] }) }, String(syn.tensions?.length || 0)), h(Text, { style: S.statLabel }, "TENSIONS")),',
  '      h(View, { style: S.statCard }, h(Text, { style: Object.assign({}, S.statNum, { color: C.emerald[600] }) }, String(syn.recommendations?.length || 0)), h(Text, { style: S.statLabel }, "ACTIONS"))',
  '    ),',
  '    syn.recommendations?.length > 0 && h(View, null,',
  '      h(View, { style: { flexDirection: "row", alignItems: "center", marginBottom: 12 } },',
  '        h(View, { style: { width: 4, height: 20, backgroundColor: C.emerald[600], borderRadius: 2, marginRight: 12 } }),',
  '        h(Text, { style: Object.assign({}, S.h3, { marginBottom: 0 }) }, "Priority Recommendations")',
  '      ),',
  '      ...syn.recommendations.slice(0, 3).map(function(rec, i) {',
  '        return h(View, { key: "r" + i, style: Object.assign({}, S.row, { marginBottom: 10, padding: 12, backgroundColor: C.white, border: "1pt solid " + C.slate[200], borderRadius: 8 }) },',
  '          h(View, { style: { width: 28, height: 28, borderRadius: 14, backgroundColor: C.emerald[600], alignItems: "center", justifyContent: "center", marginRight: 12 } },',
  '            h(Text, { style: { color: C.white, fontSize: 12, fontFamily: "Helvetica-Bold" } }, String(i + 1))',
  '          ),',
  '          h(Text, { style: Object.assign({}, S.body, { flex: 1 }) }, truncate(rec, 95))',
  '        );',
  '      })',
  '    ),',
  '    h(View, { style: S.footer }, h(Text, null, client?.company_name || "Strategic Synthesis"), h(Text, null, "Page " + pn))',
  '  );',
  '}',
  '',
  'function oppCard(opp, idx) {',
  '  var qs = QS[opp.quadrant] || QS.explore;',
  '  function bar(score, label, color) {',
  '    var pct = (Math.min(10, Math.max(0, score || 5)) / 10) * 100;',
  '    return h(View, { style: { flex: 1 } },',
  '      h(View, { style: { flexDirection: "row", justifyContent: "space-between", marginBottom: 4 } },',
  '        h(Text, { style: S.label }, label),',
  '        h(Text, { style: { fontSize: 9, fontFamily: "Helvetica-Bold", color: color } }, (score||5) + "/10")',
  '      ),',
  '      h(View, { style: { height: 6, backgroundColor: C.slate[200], borderRadius: 3 } },',
  '        h(View, { style: { width: pct + "%", height: 6, backgroundColor: color, borderRadius: 3 } })',
  '      )',
  '    );',
  '  }',
  '  return h(View, { key: "o" + idx, style: Object.assign({}, S.card, { borderLeft: "3pt solid " + (qs.borderColor || C.navy.DEFAULT) }) },',
  '    h(View, { style: Object.assign({}, S.row, { marginBottom: 12 }) },',
  '      h(View, { style: { width: 24, height: 24, borderRadius: 12, backgroundColor: qs.borderColor || C.navy.DEFAULT, alignItems: "center", justifyContent: "center", marginRight: 10 } },',
  '        h(Text, { style: { fontSize: 10, fontFamily: "Helvetica-Bold", color: C.white } }, String(idx + 1))',
  '      ),',
  '      h(Text, { style: Object.assign({}, S.h3, { flex: 1, marginBottom: 0 }) }, truncate(opp.title, 45)),',
  '      h(View, { style: Object.assign({}, S.badge, { backgroundColor: qs.backgroundColor }) },',
  '        h(Text, { style: { color: qs.color, fontSize: 7 } }, (opp.quadrant || "explore").toUpperCase())',
  '      )',
  '    ),',
  '    h(Text, { style: Object.assign({}, S.body, { marginBottom: 12 }) }, truncate(opp.description, 180)),',
  '    opp.scoring && h(View, { style: Object.assign({}, S.row, { gap: 16, marginBottom: 12, paddingTop: 12, borderTop: "1pt solid " + C.slate[200] }) },',
  '      bar(opp.scoring.marketAttractiveness, "MARKET", C.cyan[600]),',
  '      bar(opp.scoring.capabilityFit, "CAPABILITY", C.navy.DEFAULT),',
  '      bar(opp.scoring.competitiveAdvantage, "COMPETITIVE", C.emerald[600])',
  '    ),',
  '    opp.ptw?.howToWin && h(View, { style: { backgroundColor: C.slate[50], padding: 10, borderRadius: 8, marginTop: 4 } },',
  '      h(Text, { style: Object.assign({}, S.label, { marginBottom: 4 }) }, "HOW TO WIN"),',
  '      h(Text, { style: S.bodySmall }, truncate(opp.ptw.howToWin, 140))',
  '    )',
  '  );',
  '}',
  '',
  'function oppsPage(opps, client, pn, si) {',
  '  var po = opps.slice(si, si + 2);',
  '  return h(Page, { key: "op" + pn, size: "A4", style: S.page },',
  '    si === 0 && h(View, { style: { marginBottom: 20 } },',
  '      h(View, { style: { flexDirection: "row", alignItems: "center", marginBottom: 8 } },',
  '        h(View, { style: { width: 4, height: 24, backgroundColor: C.navy.DEFAULT, borderRadius: 2, marginRight: 12 } }),',
  '        h(Text, { style: Object.assign({}, S.h2, { marginBottom: 0 }) }, "Strategic Opportunities")',
  '      )',
  '    ),',
  '    ...po.map(function(o, i) { return oppCard(o, si + i); }),',
  '    h(View, { style: S.footer }, h(Text, null, client?.company_name || "Strategic Synthesis"), h(Text, null, "Page " + pn))',
  '  );',
  '}',
  '',
  'function tensionsPage(tens, client, pn) {',
  '  return h(Page, { size: "A4", style: S.page },',
  '    h(View, { style: { marginBottom: 20 } },',
  '      h(View, { style: { flexDirection: "row", alignItems: "center", marginBottom: 8 } },',
  '        h(View, { style: { width: 4, height: 24, backgroundColor: C.amber[600], borderRadius: 2, marginRight: 12 } }),',
  '        h(Text, { style: Object.assign({}, S.h2, { marginBottom: 0 }) }, "Strategic Tensions")',
  '      )',
  '    ),',
  '    ...tens.slice(0, 3).map(function(t, i) {',
  '      return h(View, { key: "t" + i, style: Object.assign({}, S.card, { borderLeft: "3pt solid " + C.amber[600] }) },',
  '        h(View, { style: Object.assign({}, S.row, { marginBottom: 10 }) },',
  '          h(View, { style: { width: 24, height: 24, borderRadius: 12, backgroundColor: C.amber[600], alignItems: "center", justifyContent: "center", marginRight: 10 } },',
  '            h(Text, { style: { fontSize: 10, fontFamily: "Helvetica-Bold", color: C.white } }, String(i + 1))',
  '          ),',
  '          h(Text, { style: Object.assign({}, S.h3, { flex: 1, marginBottom: 0 }) }, truncate(t.description, 70))',
  '        ),',
  '        t.resolutionOptions?.length > 0 && h(View, { style: { backgroundColor: C.slate[50], padding: 10, borderRadius: 8 } },',
  '          h(Text, { style: Object.assign({}, S.label, { marginBottom: 8 }) }, "RESOLUTION OPTIONS"),',
  '          ...t.resolutionOptions.slice(0, 2).map(function(opt, j) {',
  '            return h(View, { key: "ro" + j, style: Object.assign({}, S.row, { marginBottom: 6 }) },',
  '              h(View, { style: { width: 6, height: 6, borderRadius: 3, backgroundColor: opt.recommended ? C.emerald[600] : C.slate[400], marginRight: 8, marginTop: 4 } }),',
  '              h(View, { style: { flex: 1 } },',
  '                h(Text, { style: Object.assign({}, S.bodySmall, { fontFamily: opt.recommended ? "Helvetica-Bold" : "Helvetica" }) }, truncate(opt.option, 90)),',
  '                opt.recommended && h(Text, { style: { fontSize: 7, color: C.emerald[600], marginTop: 2 } }, "RECOMMENDED")',
  '              )',
  '            );',
  '          })',
  '        )',
  '      );',
  '    }),',
  '    h(View, { style: S.footer }, h(Text, null, client?.company_name || "Strategic Synthesis"), h(Text, null, "Page " + pn))',
  '  );',
  '}',
  '',
  'function appendix(syn, client, pn) {',
  '  return h(Page, { size: "A4", style: S.page },',
  '    h(View, { style: { marginBottom: 24 } },',
  '      h(View, { style: { flexDirection: "row", alignItems: "center", marginBottom: 8 } },',
  '        h(View, { style: { width: 4, height: 24, backgroundColor: C.slate[500], borderRadius: 2, marginRight: 12 } }),',
  '        h(Text, { style: Object.assign({}, S.h2, { marginBottom: 0 }) }, "Appendix: Methodology")',
  '      )',
  '    ),',
  '    h(View, { style: Object.assign({}, S.card, { marginBottom: 20 }) },',
  '      h(Text, { style: Object.assign({}, S.h3, { marginBottom: 8 }) }, "Playing to Win Framework"),',
  '      h(Text, { style: Object.assign({}, S.body, { marginBottom: 12 }) }, "This strategic synthesis uses the Playing to Win framework developed by A.G. Lafley and Roger Martin.")',
  '    ),',
  '    h(View, { style: { backgroundColor: C.amber[50], border: "1pt solid " + C.amber[100], borderRadius: 12, padding: 16 } },',
  '      h(Text, { style: Object.assign({}, S.label, { color: C.amber[600], marginBottom: 8 }) }, "IMPORTANT DISCLAIMER"),',
  '      h(Text, { style: Object.assign({}, S.bodySmall, { color: C.slate[700], lineHeight: 1.6 }) },',
  '        "This report is generated by AI. It should be used as a starting point for strategic discussions and validated with additional research and stakeholder input."',
  '      )',
  '    ),',
  '    h(View, { style: S.footer }, h(Text, null, client?.company_name || "Strategic Synthesis"), h(Text, null, "Page " + pn))',
  '  );',
  '}',
  '',
  'async function gen(syn, client, date) {',
  '  var pages = [], pn = 1;',
  '  pages.push(cover(client, date)); pn++;',
  '  pages.push(execSummary(syn, client, pn)); pn++;',
  '  var opps = syn.opportunities || [];',
  '  for (var i = 0; i < opps.length; i += 2) { pages.push(oppsPage(opps, client, pn, i)); pn++; }',
  '  var tens = syn.tensions || [];',
  '  if (tens.length > 0) { pages.push(tensionsPage(tens, client, pn)); pn++; }',
  '  pages.push(appendix(syn, client, pn));',
  '  return renderToBuffer(h(Document, { title: "Strategic Synthesis - " + (client?.company_name || "Report"), author: "Frontera AI Strategy Coach" }, ...pages));',
  '}',
  '',
  'async function main() {',
  '  try {',
  '    var chunks = [];',
  '    for await (var chunk of process.stdin) { chunks.push(chunk); }',
  '    var input = JSON.parse(Buffer.concat(chunks).toString("utf8"));',
  '    var buf = await gen(input.synthesis, input.client, input.generatedAt || new Date().toISOString());',
  '    process.stdout.write(buf);',
  '    process.exit(0);',
  '  } catch (e) {',
  '    process.stderr.write(e.message + "\\n" + (e.stack || ""));',
  '    process.exit(1);',
  '  }',
  '}',
  'main();',
].join('\n');
