import Image from 'next/image';

async function loadSharedArtefact(token: string) {
  const baseUrl = process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000';
  const res = await fetch(`${baseUrl}/api/product-strategy-agent-v2/share/${token}`, {
    cache: 'no-store',
  });
  if (!res.ok) return null;
  const data = await res.json();
  return data.artefact;
}

export default async function SharedArtefactPage({
  params,
}: {
  params: Promise<{ token: string }>;
}) {
  const { token } = await params;
  const artefact = await loadSharedArtefact(token);

  if (!artefact) {
    return (
      <div className="min-h-screen bg-slate-50 flex items-center justify-center">
        <div className="text-center p-8 bg-white rounded-2xl shadow-lg border border-slate-200 max-w-md">
          <h2 className="text-xl font-bold text-slate-900 mb-2">Link Not Found</h2>
          <p className="text-sm text-slate-600">This shared artefact link is invalid or has expired.</p>
        </div>
      </div>
    );
  }

  const content = artefact.content as Record<string, unknown>;
  const typeLabels: Record<string, string> = {
    team_brief: 'Team Brief',
    guardrails: 'Strategic Guardrails',
    okr_cascade: 'OKR Cascade',
    decision_framework: 'Decision Framework',
    stakeholder_pack: 'Stakeholder Brief',
    evidence_summary: 'Evidence Summary',
  };

  return (
    <div className="min-h-screen bg-slate-50">
      {/* Header */}
      <div className="bg-[#1a1f3a] text-white px-6 py-5">
        <div className="max-w-3xl mx-auto flex items-center gap-4">
          <div className="w-10 h-10 rounded-xl overflow-hidden flex-shrink-0">
            <Image src="/frontera-logo-F.jpg" alt="Frontera" width={40} height={40} className="w-full h-full object-cover" />
          </div>
          <div>
            <span className="text-xs font-semibold uppercase tracking-wider text-[#fbbf24]">
              {typeLabels[artefact.artefact_type] || 'Strategic Artefact'}
            </span>
            <h1 className="text-lg font-bold">{artefact.title}</h1>
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-3xl mx-auto px-6 py-8">
        <div className="bg-white border border-cyan-200 rounded-2xl p-8 shadow-sm space-y-6">
          {/* Render based on artefact type */}
          {artefact.artefact_type === 'team_brief' && (
            <TeamBriefContent content={content} />
          )}
          {artefact.artefact_type === 'guardrails' && (
            <GuardrailsContent content={content} />
          )}
          {artefact.artefact_type === 'okr_cascade' && (
            <OKRContent content={content} />
          )}
          {artefact.artefact_type === 'stakeholder_pack' && (
            <StakeholderContent content={content} />
          )}
          {artefact.artefact_type === 'decision_framework' && (
            <DecisionContent content={content} />
          )}

          {/* Generic fallback for unknown types */}
          {!['team_brief', 'guardrails', 'okr_cascade', 'stakeholder_pack', 'decision_framework'].includes(artefact.artefact_type) && (
            <pre className="text-xs text-slate-600 whitespace-pre-wrap">
              {JSON.stringify(content, null, 2)}
            </pre>
          )}
        </div>

        {/* Footer */}
        <p className="text-center text-[11px] text-slate-400 mt-6">
          Generated by Frontera Strategy Coach &bull; {new Date(artefact.updated_at || artefact.created_at).toLocaleDateString()}
        </p>
      </div>
    </div>
  );
}

// ============================================================================
// Content renderers (server components)
// ============================================================================

function TeamBriefContent({ content }: { content: Record<string, unknown> }) {
  return (
    <>
      {typeof content.strategicContext === 'string' && (
        <Section title="Strategic Context" text={content.strategicContext} />
      )}
      {typeof content.problemStatement === 'string' && (
        <Section title="Problem Statement" text={content.problemStatement} />
      )}
      {Array.isArray(content.successCriteria) && (
        <ListSection title="Success Criteria" items={content.successCriteria as string[]} />
      )}
      {typeof content.killCriteria === 'string' && (
        <div>
          <h3 className="text-xs font-semibold uppercase tracking-wider text-red-600 mb-1">Kill Criteria</h3>
          <p className="text-sm text-slate-700">{content.killCriteria}</p>
        </div>
      )}
    </>
  );
}

function GuardrailsContent({ content }: { content: Record<string, unknown> }) {
  const items = Array.isArray(content.guardrails) ? content.guardrails as Array<{ weWill: string; weWillNot: string; rationale?: string }> : [];
  return (
    <div className="space-y-4">
      {items.map((item, i) => (
        <div key={i} className="grid grid-cols-2 gap-4 p-4 bg-slate-50 rounded-xl">
          <div>
            <span className="text-[10px] font-bold uppercase tracking-wider text-emerald-600">We Will</span>
            <p className="text-sm text-slate-700 mt-1">{item.weWill}</p>
          </div>
          <div>
            <span className="text-[10px] font-bold uppercase tracking-wider text-red-500">We Will Not</span>
            <p className="text-sm text-slate-700 mt-1">{item.weWillNot}</p>
          </div>
          {item.rationale && (
            <p className="col-span-2 text-xs text-slate-500 italic">{item.rationale}</p>
          )}
        </div>
      ))}
    </div>
  );
}

function OKRContent({ content }: { content: Record<string, unknown> }) {
  const okrs = Array.isArray(content.okrs) ? content.okrs as Array<{ objective: string; keyResults: Array<{ kr: string; target: string; timeframe: string }> }> : [];
  return (
    <div className="space-y-6">
      {okrs.map((item, idx) => (
        <div key={idx}>
          <h3 className="text-base font-semibold text-slate-900 mb-3">O{idx + 1}: {item.objective}</h3>
          <div className="space-y-2 ml-4">
            {item.keyResults.map((kr, krIdx) => (
              <div key={krIdx} className="flex items-start gap-3">
                <span className="flex-shrink-0 w-7 h-7 rounded-lg bg-[#1a1f3a] text-white text-[10px] font-bold flex items-center justify-center">
                  KR{krIdx + 1}
                </span>
                <div>
                  <p className="text-sm text-slate-700">{kr.kr}</p>
                  <p className="text-xs text-slate-400">Target: {kr.target} &bull; {kr.timeframe}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      ))}
    </div>
  );
}

function StakeholderContent({ content }: { content: Record<string, unknown> }) {
  return (
    <>
      {typeof content.executiveSummary === 'string' && (
        <Section title="Executive Summary" text={content.executiveSummary} />
      )}
      {Array.isArray(content.keyImplications) && (
        <ListSection title="Key Implications" items={content.keyImplications as string[]} />
      )}
      {Array.isArray(content.whatChanges) && (
        <ListSection title="What Changes" items={content.whatChanges as string[]} />
      )}
      {Array.isArray(content.questionsToAddress) && (
        <ListSection title="Questions to Address" items={content.questionsToAddress as string[]} />
      )}
    </>
  );
}

function DecisionContent({ content }: { content: Record<string, unknown> }) {
  const framework = content.framework as { prioritise?: Array<{ rule: string; context: string }>; consider?: Array<{ rule: string; context: string }>; deprioritise?: Array<{ rule: string; context: string }> } | undefined;
  if (!framework) return null;

  const sections = [
    { key: 'prioritise' as const, label: 'Prioritise', color: 'text-emerald-700' },
    { key: 'consider' as const, label: 'Consider', color: 'text-amber-700' },
    { key: 'deprioritise' as const, label: 'Deprioritise', color: 'text-red-600' },
  ];

  return (
    <div className="space-y-6">
      {sections.map((s) => (
        <div key={s.key}>
          <h3 className={`text-xs font-bold uppercase tracking-wider ${s.color} mb-2`}>{s.label}</h3>
          <div className="space-y-2">
            {(framework[s.key] || []).map((item, i) => (
              <div key={i} className="p-3 bg-slate-50 rounded-xl">
                <p className="text-sm font-medium text-slate-900">{item.rule}</p>
                {item.context && <p className="text-xs text-slate-500 mt-0.5">{item.context}</p>}
              </div>
            ))}
          </div>
        </div>
      ))}
    </div>
  );
}

// Helper components
function Section({ title, text }: { title: string; text: string }) {
  return (
    <div>
      <h3 className="text-xs font-semibold uppercase tracking-wider text-slate-400 mb-1">{title}</h3>
      <p className="text-sm text-slate-700 leading-relaxed">{text}</p>
    </div>
  );
}

function ListSection({ title, items }: { title: string; items: string[] }) {
  return (
    <div>
      <h3 className="text-xs font-semibold uppercase tracking-wider text-slate-400 mb-1">{title}</h3>
      <ul className="space-y-1">
        {items.map((item, i) => (
          <li key={i} className="text-sm text-slate-700 flex items-start gap-2">
            <span className="w-1.5 h-1.5 rounded-full bg-[#fbbf24] mt-2 flex-shrink-0" />
            {item}
          </li>
        ))}
      </ul>
    </div>
  );
}
