'use client';

import { useState, useEffect, useCallback, useRef } from 'react';
import {
  Lightbulb,
  Loader2,
  ArrowRight,
  RefreshCw,
  Download,
  AlertTriangle,
  CheckCircle2,
  Sparkles,
  Plus,
} from 'lucide-react';
import type { SynthesisResult, StrategicOpportunity, EvidenceLink } from '@/types/synthesis';
import { OpportunityCard } from '../CanvasPanel/OpportunityCard';
import { TensionCard } from '../CanvasPanel/TensionCard';
import { RecommendationsPanel } from '../CanvasPanel/RecommendationsPanel';
import { StrategicOpportunityMap } from '../CanvasPanel/StrategicOpportunityMap';
import { OpportunityEditModal } from './OpportunityEditModal';
import { OpportunityCoachDrawer } from './OpportunityCoachDrawer';

interface SynthesisViewProps {
  conversationId: string;
  onPhaseTransition: (phase: string) => Promise<void>;
}

type ViewState = 'loading' | 'empty' | 'generating' | 'results' | 'error';

export function SynthesisView({ conversationId, onPhaseTransition }: SynthesisViewProps) {
  const [synthesis, setSynthesis] = useState<SynthesisResult | null>(null);
  const [viewState, setViewState] = useState<ViewState>('loading');
  const [error, setError] = useState<string | null>(null);
  const [isExporting, setIsExporting] = useState(false);
  const [selectedOpportunityId, setSelectedOpportunityId] = useState<string | null>(null);
  const [expandedOpportunityId, setExpandedOpportunityId] = useState<string | null>(null);
  const [isTransitioning, setIsTransitioning] = useState(false);
  const hasAutoGenerated = useRef(false);

  // CRUD state
  const [showEditModal, setShowEditModal] = useState(false);
  const [editModalMode, setEditModalMode] = useState<'create' | 'edit'>('create');
  const [editingOpportunity, setEditingOpportunity] = useState<StrategicOpportunity | undefined>(undefined);
  const [isGeneratingOne, setIsGeneratingOne] = useState(false);
  const [isSavingOpportunities, setIsSavingOpportunities] = useState(false);

  // Coach drawer state
  const [showCoachDrawer, setShowCoachDrawer] = useState(false);
  const [coachOpportunity, setCoachOpportunity] = useState<StrategicOpportunity | null>(null);
  const [coachDraft, setCoachDraft] = useState<StrategicOpportunity | undefined>(undefined);

  const opportunityCount = synthesis?.opportunities.length || 0;
  const canProceed = opportunityCount >= 2;
  const canAdd = opportunityCount < 5;

  // Fetch existing synthesis on mount
  useEffect(() => {
    let cancelled = false;

    async function fetchSynthesis() {
      try {
        const res = await fetch(
          `/api/product-strategy-agent/synthesis?conversation_id=${conversationId}`
        );
        if (!res.ok) throw new Error('Failed to fetch synthesis');

        const data = await res.json();
        if (cancelled) return;

        if (data.success && data.synthesis) {
          setSynthesis(data.synthesis);
          setViewState('results');
        } else {
          setViewState('empty');
        }
      } catch {
        if (!cancelled) {
          try {
            const cached = localStorage.getItem(`synthesis_${conversationId}`);
            if (cached) {
              setSynthesis(JSON.parse(cached));
              setViewState('results');
              return;
            }
          } catch { /* ignore */ }
          setViewState('empty');
        }
      }
    }

    fetchSynthesis();
    return () => { cancelled = true; };
  }, [conversationId]);

  // Auto-generate if no synthesis exists
  useEffect(() => {
    if (viewState === 'empty' && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true;
      void handleGenerate();
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [viewState]);

  const handleGenerate = useCallback(async () => {
    setViewState('generating');
    setError(null);

    try {
      const res = await fetch('/api/product-strategy-agent/synthesis', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ conversation_id: conversationId }),
      });

      const data = await res.json();

      if (!res.ok) {
        const msg = data.details ? `${data.error}: ${data.details}` : data.error || 'Generation failed';
        setError(msg);
        setViewState('error');
        return;
      }

      if (data.success && data.synthesis) {
        setSynthesis(data.synthesis);
        setViewState('results');
        try {
          localStorage.setItem(`synthesis_${conversationId}`, JSON.stringify(data.synthesis));
        } catch { /* quota */ }
      }
    } catch {
      setError('An unexpected error occurred. Please try again.');
      setViewState('error');
    }
  }, [conversationId]);

  const handleExportPDF = useCallback(async () => {
    setIsExporting(true);
    try {
      const res = await fetch(
        `/api/product-strategy-agent/synthesis/export?conversation_id=${conversationId}`
      );
      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error || 'Export failed');
      }
      const blob = await res.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `Strategic-Synthesis-${new Date().toISOString().split('T')[0]}.pdf`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      a.remove();
    } catch (err) {
      console.error('Export error:', err);
    } finally {
      setIsExporting(false);
    }
  }, [conversationId]);

  const handleOpportunityClick = useCallback((id: string) => {
    setSelectedOpportunityId(id);
    setExpandedOpportunityId(id);
    const el = document.getElementById(`opportunity-${id}`);
    el?.scrollIntoView({ behavior: 'smooth', block: 'center' });
  }, []);

  const handleContinueToBets = useCallback(async () => {
    setIsTransitioning(true);
    try {
      await onPhaseTransition('bets');
    } finally {
      setIsTransitioning(false);
    }
  }, [onPhaseTransition]);

  // ========== CRUD Handlers ==========

  const saveOpportunities = useCallback(async (opportunities: StrategicOpportunity[]) => {
    setIsSavingOpportunities(true);
    try {
      const res = await fetch('/api/product-strategy-agent/synthesis', {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ conversation_id: conversationId, opportunities }),
      });

      const data = await res.json();
      if (!res.ok) throw new Error(data.error || 'Failed to save');

      if (data.success && data.synthesis) {
        setSynthesis(data.synthesis);
        try {
          localStorage.setItem(`synthesis_${conversationId}`, JSON.stringify(data.synthesis));
        } catch { /* quota */ }
      }
    } catch (err) {
      console.error('Error saving opportunities:', err);
    } finally {
      setIsSavingOpportunities(false);
    }
  }, [conversationId]);

  const handleEditOpportunity = useCallback((opp: StrategicOpportunity) => {
    setEditingOpportunity(opp);
    setEditModalMode('edit');
    setShowEditModal(true);
  }, []);

  const handleAddOpportunity = useCallback(() => {
    setEditingOpportunity(undefined);
    setEditModalMode('create');
    setShowEditModal(true);
  }, []);

  const handleDeleteOpportunity = useCallback((opportunityId: string) => {
    if (!synthesis) return;
    const remaining = synthesis.opportunities.filter(o => o.id !== opportunityId);
    if (remaining.length === 0) {
      alert('Cannot delete the last opportunity.');
      return;
    }
    if (!confirm('Delete this strategic hypothesis? This action cannot be undone.')) return;
    void saveOpportunities(remaining);
  }, [synthesis, saveOpportunities]);

  const handleSaveFromModal = useCallback((opp: StrategicOpportunity) => {
    if (!synthesis) return;
    let updated: StrategicOpportunity[];
    if (editModalMode === 'edit') {
      updated = synthesis.opportunities.map(o => o.id === opp.id ? opp : o);
    } else {
      updated = [...synthesis.opportunities, opp];
    }
    void saveOpportunities(updated);
    setShowEditModal(false);
    setEditingOpportunity(undefined);
  }, [synthesis, editModalMode, saveOpportunities]);

  const handleGenerateOne = useCallback(async () => {
    if (!canAdd || isGeneratingOne) return;
    setIsGeneratingOne(true);
    try {
      const res = await fetch('/api/product-strategy-agent/synthesis/generate-one', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ conversation_id: conversationId }),
      });

      const data = await res.json();
      if (!res.ok) {
        console.error('Generate one error:', data.error);
        return;
      }

      if (data.success && data.opportunity && synthesis) {
        const updated: SynthesisResult = {
          ...synthesis,
          opportunities: [...synthesis.opportunities, data.opportunity],
          userEdited: true,
        };
        setSynthesis(updated);
        try {
          localStorage.setItem(`synthesis_${conversationId}`, JSON.stringify(updated));
        } catch { /* quota */ }
      }
    } catch (err) {
      console.error('Generate one network error:', err);
    } finally {
      setIsGeneratingOne(false);
    }
  }, [canAdd, isGeneratingOne, conversationId, synthesis]);

  const handleAskCoach = useCallback((draft: StrategicOpportunity) => {
    setCoachOpportunity(draft);
    setCoachDraft(draft);
    setShowCoachDrawer(true);
  }, []);

  // Check if an opportunity has been edited from original
  const isOpportunityEdited = useCallback((oppId: string) => {
    if (!synthesis?.originalOpportunities) return false;
    const original = synthesis.originalOpportunities.find(o => o.id === oppId);
    if (!original) return true; // New opportunity = "edited" (user-added)
    const current = synthesis.opportunities.find(o => o.id === oppId);
    if (!current) return false;
    return JSON.stringify(original) !== JSON.stringify(current);
  }, [synthesis]);

  // Get original for revert
  const getOriginalOpportunity = useCallback((oppId: string) => {
    return synthesis?.originalOpportunities?.find(o => o.id === oppId);
  }, [synthesis]);

  // Loading state
  if (viewState === 'loading') {
    return (
      <div className="flex-1 overflow-y-auto">
        <div className="max-w-2xl mx-auto px-6 py-12">
          <div className="text-center">
            <div className="w-12 h-12 border-2 border-[#1a1f3a] border-t-transparent rounded-full animate-spin mx-auto mb-4" />
            <p className="text-sm text-slate-600">Loading synthesis...</p>
          </div>
        </div>
      </div>
    );
  }

  // Generating state
  if (viewState === 'generating') {
    return (
      <div className="flex-1 overflow-y-auto">
        <div className="max-w-2xl mx-auto px-6 py-12 animate-entrance">
          <div className="text-center mb-8">
            <div className="inline-flex items-center justify-center w-20 h-20 rounded-2xl bg-purple-50 mb-6">
              <Sparkles className="w-10 h-10 text-purple-600 animate-pulse" />
            </div>
            <h2 className="text-2xl font-bold text-slate-900 mb-2">Synthesizing Your Research</h2>
            <p className="text-sm text-slate-500 max-w-md mx-auto">
              Analyzing territory insights across Company, Customer, and Market to identify strategic patterns...
            </p>
          </div>

          <div className="bg-white border border-slate-100 rounded-2xl p-6 shadow-sm max-w-md mx-auto">
            <div className="space-y-4">
              {[
                'Reading territory research...',
                'Cross-referencing insights...',
                'Applying Playing to Win framework...',
                'Scoring strategic opportunities...',
                'Identifying tensions & recommendations...',
              ].map((step, i) => (
                <div key={i} className="flex items-center gap-3" style={{ animationDelay: `${i * 2}s` }}>
                  <div className="w-6 h-6 rounded-full bg-purple-100 flex items-center justify-center flex-shrink-0">
                    <Loader2 className="w-3 h-3 text-purple-600 animate-spin" style={{ animationDelay: `${i * 0.5}s` }} />
                  </div>
                  <span className="text-xs text-slate-600">{step}</span>
                </div>
              ))}
            </div>
            <div className="mt-6 pt-4 border-t border-slate-100 text-center">
              <p className="text-[10px] text-slate-400 uppercase tracking-wider font-semibold">
                This typically takes 15-30 seconds
              </p>
            </div>
          </div>
        </div>
      </div>
    );
  }

  // Error state
  if (viewState === 'error') {
    return (
      <div className="flex-1 overflow-y-auto">
        <div className="max-w-2xl mx-auto px-6 py-12 animate-entrance">
          <div className="text-center mb-6">
            <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-red-50 mb-4">
              <AlertTriangle className="w-8 h-8 text-red-500" />
            </div>
            <h2 className="text-xl font-bold text-slate-900 mb-2">Synthesis Failed</h2>
          </div>
          <div className="bg-red-50 border border-red-200 rounded-xl p-4 mb-6">
            <p className="text-sm text-red-700">{error}</p>
          </div>
          <div className="text-center">
            <button
              onClick={handleGenerate}
              className="inline-flex items-center gap-2 px-6 py-3 rounded-lg bg-[#fbbf24] text-sm font-semibold text-slate-900 transition-all hover:bg-[#f59e0b] focus:outline-none focus:ring-2 focus:ring-[#fbbf24] focus:ring-offset-2"
            >
              <RefreshCw className="w-4 h-4" />
              Try Again
            </button>
          </div>
        </div>
      </div>
    );
  }

  // Empty state
  if (viewState === 'empty' || !synthesis) {
    return (
      <div className="flex-1 overflow-y-auto">
        <div className="max-w-2xl mx-auto px-6 py-12 animate-entrance">
          <div className="text-center">
            <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-purple-50 mb-4">
              <Lightbulb className="w-8 h-8 text-purple-600" />
            </div>
            <h2 className="text-xl font-bold text-slate-900 mb-2">Generate Strategic Synthesis</h2>
            <p className="text-sm text-slate-500 mb-6 max-w-md mx-auto">
              Your research is ready. Generate AI-powered strategic opportunities using the Playing to Win framework.
            </p>
            <button
              onClick={handleGenerate}
              className="inline-flex items-center gap-2 px-6 py-3 rounded-lg bg-[#fbbf24] text-sm font-semibold text-slate-900 transition-all hover:bg-[#f59e0b] hover:scale-105 focus:outline-none focus:ring-2 focus:ring-[#fbbf24] focus:ring-offset-2"
            >
              <Sparkles className="w-4 h-4" />
              Generate Strategic Insights
            </button>
          </div>
        </div>
      </div>
    );
  }

  // Results view
  return (
    <div className="flex-1 overflow-y-auto">
      <div className="max-w-2xl mx-auto px-6 py-6 space-y-6 animate-entrance">
        {/* Phase header */}
        <div className="text-center mb-2">
          <div className="inline-flex items-center justify-center w-12 h-12 rounded-2xl bg-purple-50 mb-3">
            <Lightbulb className="w-6 h-6 text-purple-600" />
          </div>
          <h1 className="text-xl font-bold text-slate-900">Strategic Synthesis</h1>
          <p className="text-xs text-slate-500 mt-1">
            {synthesis.metadata.territoriesIncluded.length} territories · {synthesis.metadata.researchAreasCount} research areas analyzed
          </p>
        </div>

        {/* Executive Summary */}
        {synthesis.executiveSummary && (
          <div className="bg-white border border-purple-200 rounded-2xl p-5 shadow-sm">
            <span className="text-[10px] font-semibold uppercase tracking-wider text-purple-600">
              Executive Summary
            </span>
            <p className="text-sm text-slate-700 mt-2 leading-relaxed">
              {synthesis.executiveSummary}
            </p>
          </div>
        )}

        {/* Strategic Opportunity Map */}
        {synthesis.opportunities.length > 0 && (
          <StrategicOpportunityMap
            opportunities={synthesis.opportunities}
            onOpportunityClick={handleOpportunityClick}
            selectedOpportunityId={selectedOpportunityId || undefined}
          />
        )}

        {/* Opportunity Cards */}
        {synthesis.opportunities.length > 0 && (
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Lightbulb className="w-4 h-4 text-purple-600" />
                <h2 className="text-base font-bold text-slate-900">
                  Strategic Hypotheses ({opportunityCount}/5)
                </h2>
              </div>
              <div className="flex items-center gap-2">
                <button
                  onClick={handleAddOpportunity}
                  disabled={!canAdd || isSavingOpportunities}
                  className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold text-slate-700 bg-white border border-slate-200 rounded-lg hover:bg-slate-50 hover:border-slate-300 transition-all disabled:opacity-40 disabled:cursor-not-allowed"
                >
                  <Plus className="w-3 h-3" />
                  Add
                </button>
                <button
                  onClick={handleGenerateOne}
                  disabled={!canAdd || isGeneratingOne || isSavingOpportunities}
                  className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold text-purple-700 bg-purple-50 border border-purple-200 rounded-lg hover:bg-purple-100 hover:border-purple-300 transition-all disabled:opacity-40 disabled:cursor-not-allowed"
                >
                  {isGeneratingOne ? (
                    <Loader2 className="w-3 h-3 animate-spin" />
                  ) : (
                    <Sparkles className="w-3 h-3" />
                  )}
                  {isGeneratingOne ? 'Generating...' : 'Generate One More'}
                </button>
              </div>
            </div>
            <p className="text-xs text-slate-500 -mt-2">
              Each pairs a Where to Play choice with a How to Win advantage
            </p>
            <div className="space-y-4">
              {synthesis.opportunities.map((opportunity) => (
                <div key={opportunity.id} id={`opportunity-${opportunity.id}`}>
                  <OpportunityCard
                    opportunity={opportunity}
                    isExpanded={expandedOpportunityId === opportunity.id}
                    onToggleExpand={() =>
                      setExpandedOpportunityId(
                        expandedOpportunityId === opportunity.id ? null : opportunity.id
                      )
                    }
                    onEvidenceClick={(evidence: EvidenceLink) => {
                      console.log('Navigate to evidence:', evidence);
                    }}
                    onEdit={handleEditOpportunity}
                    onDelete={handleDeleteOpportunity}
                    isEdited={isOpportunityEdited(opportunity.id)}
                  />
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Strategic Tensions */}
        {synthesis.tensions && synthesis.tensions.length > 0 && (
          <div className="space-y-3">
            <div className="flex items-center gap-2">
              <AlertTriangle className="w-4 h-4 text-amber-500" />
              <h2 className="text-base font-bold text-slate-900">
                Strategic Tensions ({synthesis.tensions.length})
              </h2>
            </div>
            <div className="space-y-3">
              {synthesis.tensions.map((tension) => (
                <TensionCard key={tension.id} tension={tension} />
              ))}
            </div>
          </div>
        )}

        {/* Recommendations */}
        {synthesis.recommendations && synthesis.recommendations.length > 0 && (
          <RecommendationsPanel recommendations={synthesis.recommendations} />
        )}

        {/* Actions bar */}
        <div className="flex items-center justify-center gap-3 pt-2">
          <button
            onClick={handleExportPDF}
            disabled={isExporting}
            className="inline-flex items-center gap-2 px-4 py-2 rounded-lg border border-cyan-300 bg-white text-xs font-semibold text-slate-700 transition-all hover:bg-cyan-50 disabled:opacity-50"
          >
            {isExporting ? (
              <Loader2 className="w-3.5 h-3.5 animate-spin" />
            ) : (
              <Download className="w-3.5 h-3.5" />
            )}
            {isExporting ? 'Exporting...' : 'Export PDF'}
          </button>
          <button
            onClick={handleGenerate}
            disabled={false}
            className="inline-flex items-center gap-2 px-4 py-2 rounded-lg border border-slate-200 bg-white text-xs font-semibold text-slate-500 transition-all hover:bg-slate-50 disabled:opacity-50"
          >
            <RefreshCw className="w-3.5 h-3.5" />
            Regenerate
          </button>
        </div>

        {/* Phase transition gating */}
        {canProceed ? (
          <div className="bg-gradient-to-r from-emerald-50 to-cyan-50 border border-emerald-200 rounded-2xl p-5 text-center">
            <div className="flex items-center justify-center gap-2 mb-2">
              <CheckCircle2 className="w-5 h-5 text-emerald-600" />
              <h3 className="text-sm font-bold text-slate-900">Synthesis Complete</h3>
            </div>
            <p className="text-xs text-slate-600 mb-4 max-w-md mx-auto leading-relaxed">
              Your strategic opportunities are mapped. Now transform these insights into testable strategic bets with clear hypotheses and success criteria.
            </p>
            <button
              onClick={handleContinueToBets}
              disabled={isTransitioning}
              className="inline-flex items-center gap-2 px-6 py-3 rounded-lg bg-[#fbbf24] text-sm font-semibold text-slate-900 transition-all duration-300 hover:bg-[#f59e0b] hover:scale-105 focus:outline-none focus:ring-2 focus:ring-[#fbbf24] focus:ring-offset-2 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {isTransitioning ? 'Transitioning...' : 'Continue to Strategic Bets'}
              <ArrowRight className="w-4 h-4" />
            </button>
          </div>
        ) : (
          <div className="bg-gradient-to-r from-amber-50 to-orange-50 border border-amber-200 rounded-2xl p-5 text-center">
            <div className="flex items-center justify-center gap-2 mb-2">
              <AlertTriangle className="w-5 h-5 text-amber-600" />
              <h3 className="text-sm font-bold text-slate-900">More Hypotheses Needed</h3>
            </div>
            <p className="text-xs text-slate-600 mb-4 max-w-md mx-auto leading-relaxed">
              Add at least 2 strategic hypotheses to proceed to Strategic Bets. You currently have {opportunityCount}.
              Use the &ldquo;Add&rdquo; or &ldquo;Generate One More&rdquo; buttons above.
            </p>
            <button
              disabled
              className="inline-flex items-center gap-2 px-6 py-3 rounded-lg bg-slate-200 text-sm font-semibold text-slate-400 cursor-not-allowed"
            >
              Continue to Strategic Bets
              <ArrowRight className="w-4 h-4" />
            </button>
          </div>
        )}

        {/* Bottom spacing */}
        <div className="h-4" />
      </div>

      {/* Edit Modal */}
      {showEditModal && (
        <OpportunityEditModal
          mode={editModalMode}
          opportunity={editingOpportunity}
          originalOpportunity={editingOpportunity ? getOriginalOpportunity(editingOpportunity.id) : undefined}
          onSave={handleSaveFromModal}
          onClose={() => {
            setShowEditModal(false);
            setEditingOpportunity(undefined);
          }}
          onAskCoach={handleAskCoach}
        />
      )}

      {/* Coach Drawer */}
      {coachOpportunity && (
        <OpportunityCoachDrawer
          isOpen={showCoachDrawer}
          onClose={() => setShowCoachDrawer(false)}
          opportunity={coachOpportunity}
          userDraft={coachDraft}
          conversationId={conversationId}
        />
      )}
    </div>
  );
}
